#!/bin/bash
# Trial 9: Job Lifecycle — Submit, Monitor, Cancel, Inspect
# ===========================================================
# A walkthrough of the full lifecycle of a Slurm job.
#
# Run each section's commands from the LOGIN NODE.

echo "============================================================"
echo "TRIAL 9: Slurm Job Lifecycle"
echo "============================================================"
echo ""

echo "=== STEP 1: Submit a job ==="
echo ""
echo "  # Submit a batch job"
echo "  sbatch ~/rl-rewardhacking/cluster-tutorial/03_sbatch_job.sbatch"
echo "  # -> 'Submitted batch job 12345'"
echo ""
echo "  # Or submit an array job"
echo "  sbatch ~/rl-rewardhacking/cluster-tutorial/05_array_job.sbatch"
echo "  # -> 'Submitted batch job 12346'"
echo ""

echo "=== STEP 2: Monitor your jobs ==="
echo ""
echo "  # List your jobs (shows state: PD=pending, R=running, CG=completing)"
echo "  squeue -u \$USER"
echo ""
echo "  # More detail (start time, node, time used)"
echo "  squeue -u \$USER -o '%.8i %.9P %.20j %.2t %.10M %.6D %.20R'"
echo ""
echo "  # Watch jobs update live (refreshes every 2s)"
echo "  watch -n 2 squeue -u \$USER"
echo ""
echo "  # Estimated start time for pending jobs"
echo "  squeue -u \$USER --start"
echo ""

echo "=== STEP 3: Inspect a running or completed job ==="
echo ""
echo "  # Detailed info about a specific job"
echo "  scontrol show job <JOBID>"
echo ""
echo "  # See which node your job is on"
echo "  squeue -u \$USER -o '%.8i %.20j %N'"
echo ""
echo "  # View job's resource usage after it finishes"
echo "  sacct -j <JOBID> --format=JobID,JobName,Elapsed,MaxRSS,State,ExitCode"
echo ""
echo "  # View efficiency (CPU/memory utilization)"
echo "  seff <JOBID>"
echo ""

echo "=== STEP 4: Read job output ==="
echo ""
echo "  # Logs go to the --output path in your sbatch script"
echo "  cat ~/slurm_logs/trial3-<JOBID>.log"
echo ""
echo "  # Tail a log in real-time while job runs"
echo "  tail -f ~/slurm_logs/trial3-<JOBID>.log"
echo ""
echo "  # Or attach to the job with srun --overlap (see Trial 7)"
echo "  srun --overlap --pty --jobid <JOBID> bash"
echo ""

echo "=== STEP 5: Cancel jobs ==="
echo ""
echo "  # Cancel a specific job"
echo "  scancel <JOBID>"
echo ""
echo "  # Cancel all your jobs"
echo "  scancel -u \$USER"
echo ""
echo "  # Cancel a specific array task (e.g., task 2 of array job 12346)"
echo "  scancel 12346_2"
echo ""
echo "  # Cancel all pending jobs (keep running ones)"
echo "  scancel -u \$USER --state=PENDING"
echo ""

echo "=== STEP 6: Check cluster state ==="
echo ""
echo "  # Quick GPU summary (custom Goodfire command)"
echo "  count"
echo ""
echo "  # Visual GPU dashboard"
echo "  gpudash"
echo ""
echo "  # Partition and node overview"
echo "  sinfo"
echo ""
echo "  # Per-node status"
echo "  sinfo -N -O 'Partition:24,NodeList:30,StateLong'"
echo ""
echo "  # Find idle nodes"
echo "  sinfo -N -O 'Partition:24,NodeList:30,StateLong' | grep idle"
echo ""

echo "=== STEP 7: Check past jobs ==="
echo ""
echo "  # Your jobs from the last 24 hours"
echo "  sacct --starttime=now-1day -u \$USER --format=JobID,JobName,State,Elapsed,MaxRSS"
echo ""
echo "  # Your jobs from the last 7 days"
echo "  sacct --starttime=now-7days -u \$USER --format=JobID,JobName,State,Elapsed,ExitCode"
echo ""
echo "============================================================"
echo "Tip: bookmark this file as a quick reference!"
echo "============================================================"
